### ISSUE TITLE
Wrong attribution for License

### ISSUE THREAD

**Issue by jerroydmoore** [amekkawi/cwlogs-writable#3]
Your license is wrong.

Since this is a fork of [bunyan-cloudwatch](https://github.com/mirkokiefer/bunyan-cloudwatch),
and since that software is licensed under MIT under copyright of Mirko Kiefer,
and since this repository is licensed under MIT under copyright of Andre Mekkawi,
it appears your license should be updated to be under copyright of Mirko Kiefer.

**Comment by amekkawi** [comment]
Hi jerroydmoore,

This is actually a rewrite of bunyan-cloudwatch and not a fork. To make as much of a drop-in replacement for bunyan-cloudwatch as possible, I used the same names for options, properties and methods.

I should give credit to bunyan-cloudwatch as the inspiration and basis of this library though. I'll add it to the README.

**Comment by amekkawi** [comment]
Closing in favor of #6 for updating the README. Let me know if you still have issues with the copyright.

**Comment by jerroydmoore** [comment]
I see! I assumed this was a major refactor.
