### ISSUE TITLE
Rev version to 1.0.0 (production ready)

### ISSUE THREAD

**Issue by jerroydmoore** [amekkawi/cwlogs-writable#5]
The current version of v0.1.0. node modules that are production-ready are >=1.0.0. If this module is production ready, I recommend revving to 1.0.0, to encourage adoption of this module by other nodejs developers.

**Comment by amekkawi** [comment]
Hi jerroydmoore,

Thanks for the reminder. While I have a full test suite for the library, I'm waiting until we use this library for one of our production apps before I bump it to v1.0.0. That will happen in the next few weeks.

**Comment by jerroydmoore** [comment]
Fantastic. I'm going to use the library as a drop in replacement for bunyan-cloudwatch. I'm hoping it will address the network connectivity issue I'm experiencing

**Comment by amekkawi** [comment]
@jerroydmoore Have you encountered any issues with the library? Getting close to v1.0.0.

**Comment by amekkawi** [comment]
Running in production for a while now. Bumped to v1.0.0
